Abdulrahman
EfficiencyS/dev.efficiencys.com.sa pull request #1
Opened 2021-04-11 14:21 UTC by Abdarhman636

2021-04-13 09:37 UTC, Mo9a7i requested changes
سلام عبدالرحمن, مر عالملاحظات اللي كتبتها لك هنا وعدلها واعمل بش ثاني

2021-04-13 09:37 UTC, Mo9a7i commented on assets/css/styles.css
> +    color: white;
ايش ضرورة هذا التعديل ؟

2021-04-13 09:37 UTC, Mo9a7i commented on FAQ.html
> +                            <li><a href="https://efficiencys.com.sa/#partners#partners" class="nav-link px-2 link-dark">Partners</a></li>
ليش partners متكررة هنا

2021-04-13 09:37 UTC, Mo9a7i commented on FAQ.html
> +                            <li><a href="book-a-tour.html" class="nav-link px-2 link-dark">Contact</a></li>
كونتاكت يودي ل بوك ا توور ؟
خليه يودي لفورم الكونتاكت اللي بنفس الصفحة, زي بارتنرز
وضيف لنك سميه book a tour

2021-04-13 09:37 UTC, Mo9a7i commented on about-us.html
> +                    <li><a href="book-a-tour.html" class="nav-link px-2 link-dark">Contact</a></li>
سيم , عدل اللينك هنا حق الكونتاكت والبوك ا تور

2021-04-13 09:37 UTC, Mo9a7i commented on book-a-tour.html
> +        <meta content="Modern fully-equipped shared and individual office spaces that suit all businesses. We help you be efficient by providing your business with the proper place to get things done
دسكربشن الصفحة مفروض يتغير, هذي صفحة البوك ا توور

2021-04-13 09:37 UTC, Mo9a7i commented on book-a-tour.html
> +                    <li><a href="book-a-tour.html" class="nav-link px-2 link-dark">Contact</a></li>
سيم

2021-04-13 09:37 UTC, Mo9a7i commented on book-a-tour.html
> +        <div class="contact-box col-lg-3 py-5 px-5">
كونتاكت بوكس خذه كبي بيست من الرئيسية,

2021-04-13 09:37 UTC, Mo9a7i commented on book-a-tour.html
> +                <a type="button" class="btn btn-light" href="tel:+966581115550"><i class="fas fa-phone-alt"></i> Book now</a>
شيل تايب بتن من كل اللينكات اللي كأنها زر, كلاس السي إس إٍس يكفي,, هذا يخلي عرضها بالجوال خايس

2021-04-13 09:37 UTC, Mo9a7i commented on book-a-tour.html
> +                book a tour</h1>
يا بوك ا تور, يا كونتاكت اس, وحدة من الثنتين, كل فورم مفروض له هدف

2021-04-13 09:37 UTC, Mo9a7i commented on index.html
> +        <!-- <link rel="preload" href="assets/css/styles.css" as="style">
ليه شلتهم ؟

2021-04-13 09:37 UTC, Mo9a7i commented on jobs.html
> +        <meta content="Modern fully-equipped shared and individual office spaces that suit all businesses. We help you be efficient by providing your business with the proper place to get things done
غير الدسكربشن بما يتناسب مع محتوى الصفحة

2021-04-13 09:37 UTC, Mo9a7i commented on jobs.html
> +        <title>Efficinecy Center | Apply for a job </title>
التايتل ترتيبه
الصفحة الحالية | الصفحة الاعلى منها

أبلاي فور جوبز أول


وحد الطريقة بكل الصفحات

2021-04-13 09:37 UTC, Mo9a7i commented on privacy-poilcy.html
> -                                <li><a href="#partners" class="nav-link px-2 link-dark">Partners</a></li>
تأكد ان الهيدر بكل الصفحات كبي بيست
<header>

2021-04-13 10:20 UTC, Abdarhman636 commented on assets/css/styles.css
> +    color: white;
تغير لون البرجراف في صفحة بوك ا تور ( البوكس الاسود الي ع اليمين)

2021-04-20 09:08 UTC, Mo9a7i requested changes
شيك الملاحظات الباقية وشطبها عبدالرحمن خلاص ماباقي الا ثنتين ونعتمد ان شاء الله

2021-04-20 09:08 UTC, Mo9a7i commented on book-a-tour.html
> +        <div class="contact-box col-lg-3 py-5 px-5">
شصار هنا ؟

2021-04-20 09:08 UTC, Mo9a7i commented on book-a-tour.html
> +                <a type="button" class="btn btn-light" href="tel:+966581115550"><i class="fas fa-phone-alt"></i> Book now</a>
وهنا ؟

2021-04-22 09:30 UTC, Abdarhman636 commented
> شيك الملاحظات الباقية وشطبها عبدالرحمن خلاص ماباقي الا ثنتين ونعتمد ان شاء الله

اول ملاحظة كان خطا وعدلته
ثاني ملاحظة عدلت الزر بواحد من بوتستراب جاهز

2021-05-24 05:28 UTC, merged